import type { Metadata } from "next";
import "./globals.css";
import Container from "./components/common/container/container";

export const metadata: Metadata = {
  title: "Tec Zone",
  description: "Generated by create Tec Zone",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <Container>{children}</Container>
      </body>
    </html>
  );
}
